### ISSUE TITLE
support autocomplete image size snippets

### ISSUE THREAD

**Issue by bobby169** [kisstkondoros/gutter-preview#121]
```css
.arrow {
        background: url(./images/pan-arrow.png) no-repeat;

        /* Please support autocomplete image size snippets */
        background-size:  232px 251px;
        width: 232px;
        height: 251px;
}
```
