### ISSUE TITLE
webp images doesnot show up

### ISSUE THREAD

**Issue by john1jan** [kisstkondoros/gutter-preview#72]

**Comment by kisstkondoros** [comment]
Which version have you tried this with?
I've just tested and it works fine with vscode version 1.40.2 and extension version 0.24.2.

I'll close this ticket because of insufficient information and the because it seems to work just fine.

You can test it with the latest version from vscode and from the extension (see versions above) with a simple index.css file with the following content:
```css
html {
    background: url('https://www.gstatic.com/webp/gallery/1.webp');
}
```
The image should show up on the gutter and if you hover your mouse over the link.
